const ALBUMS_LOADING = "ALBUMS_LOADING";
const ALBUMS_SUCCESS = "ALBUMS_SUCCESS";
const ALBUMS_FAILURE = "ALBUMS_FAILURE";

const ARTIST_ALBUMS = "ARTIST_ALBUMS";

const ADD_ALBUM = "ADD_ALBUM";

export {ALBUMS_LOADING, ALBUMS_SUCCESS, ALBUMS_FAILURE, ARTIST_ALBUMS, ADD_ALBUM};